### ISSUE TITLE
有可能添加更多注释吗= =

### ISSUE THREAD

**Issue by shinonomeow** [Gibberer/pcr-script#10]
我有在努力理解了

**Comment by AlphaBoom** [comment]
注释随缘的，其实工程逻辑很简单，大量的代码都是处理流程的，例如在执行一个任务时需要进行若干的点击行为。
核心逻辑Action：
1. 要点击哪里  ClickAction
2. 当前界面是否是预期的界面 MatchAction
> 判断点击哪里可以直接传入坐标，或者通过图片模板匹配来找到坐标

除了上面的逻辑之外，只剩下如何操作对应的模拟器或设备了
1. simulator   如何连接对应模拟器
2. driver        如何操控对应模拟器

可以忽略大量Robot中组合action的代码，自己想如何组合Action达成目标就好了。

**Comment by shinonomeow** [comment]
> 注释随缘的，其实工程逻辑很简单，大量的代码都是处理流程的，例如在执行一个任务时需要进行若干的点击行为。 核心逻辑Action：
> 
> 1. 要点击哪里  ClickAction
> 2. 当前界面是否是预期的界面 MatchAction
> 
> > 判断点击哪里可以直接传入坐标，或者通过图片模板匹配来找到坐标
> 
> 除了上面的逻辑之外，只剩下如何操作对应的模拟器或设备了
> 
> 1. simulator   如何连接对应模拟器
> 2. driver        如何操控对应模拟器
> 
> 可以忽略大量Robot中组合action的代码，自己想如何组合Action达成目标就好了。

你好，我在尝试写driver.click()中的107行的代码
if __name__ == '__main__':
    def winfun(hwnd, lparam):
        subtitle = win32gui.GetWindowText(hwnd)
        print(subtitle)
        if subtitle == 'TheRender':
            print(subtitle)
            return  hwnd

hwin = win32gui.FindWindow('LDPlayerMainFrame', '雷电模拟器')
subhwin = win32gui.EnumChildWindows(hwin, winfun, None)
ret = win32gui.GetWindowRect(subhwin)
print(ret)
print(ret[2]-ret[0],ret[3]-ret[1])

报错 pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')
但是输出中确实是有这个窗口
TheRender
TheRender
sub
输出hwin是 (1623, 93, 2291, 477)  尺寸是668 384 也不是设定好的960*540 挺迷惑的，我对mumu运行时也显示同样的尺寸。
请问是什么原因呢
主要我在运行main的时候一直在changeaccount转，不停的点击同一个地方，所以想着是不是出了什么问题

**Comment by AlphaBoom** [comment]
1. 如果window对显示设置了缩放（如果连接多个屏幕，每个屏幕是可以单独设置的），那么这种方式获取到的窗口大小就不会是960*540需要额外加上缩放的影响（另外不要手动拖拽调节窗口大小，这个也会影响）
2. suhwin的获取的写法有些问题，应该在回调方法winfun中赋值，而不是直接等于EnumChildWindows的返回值
---
如果上述问题无法解决可以更换使用ADBDriver

不停点击一个地方的问题，可以看下截图是否正确，把截图的内容输出文件检查下是否完整以及图片尺寸是否正确
> 在欢迎页面的逻辑是点击右上角，直至点出登录窗口后执行登录账号逻辑

**Comment by shinonomeow** [comment]
感谢，函数返回赋值确实出问题了，返回后的值还是None，所以显示缩放必须是100%是吗，设置为100%后数据就正常了

**Comment by AlphaBoom** [comment]
缩放只影响使用winapi的点击事件，可以通过获取当前屏幕缩放比例，然后在点击的实现里把960x540的点击坐标数据转换为正确的点击坐标，DNADBDriver里实现了获取第一个屏幕缩放的方法，可以参考下，如果你的主屏幕不是最左边的可以适当修改下
