### ISSUE TITLE
添加错误判断功能请求

### ISSUE THREAD

**Issue by Loukyuu1120** [Gibberer/pcr-script#11]
大佬，脚本可不可以添加关于一直判断网络连接错误超时的判断，并会点击相应按钮然后再做没完成的任务进程这一功能。

**Comment by AlphaBoom** [comment]
![image](https://user-images.githubusercontent.com/30779939/174799554-babb8aff-2458-4caa-a0b4-631d6c9cdbab.png)
这种错误么

**Comment by Loukyuu1120** [comment]
对的，还有这个
![image](https://user-images.githubusercontent.com/29080642/175016591-796da784-ce15-4ed2-9f7b-f2f27b69f630.png)

**Comment by AlphaBoom** [comment]
关于“连接超时“这种错误 你可以提供一个方便的重现路径么。
> 通过关闭模拟器网络的方式是“网络连接错误”

**Comment by Loukyuu1120** [comment]
我能想到的是把电脑连接的路由器网络关闭，就可以复现这样的错误

**Comment by Loukyuu1120** [comment]
> 

把PC的网卡禁用应该也能重现

**Comment by AlphaBoom** [comment]
该问题只处理“返回标题页”，当发现网络错误时会重头开始重新执行当前任务。
局限性:只有当前任务可以无限制时间持续执行时才能够生效(假设一个任务执行超过30s后就会超时跳过任务的话，那么这个策略就无法在该任务上生效)
