### ISSUE TITLE
shop_buy疑似点击位置有偏差？

### ISSUE THREAD

**Issue by madoka315** [Gibberer/pcr-script#13]
最新代码，使用雷电模拟器9，960*540分辨率，其他任务没发现问题，但在商店购买时按默认配置文件的：

    - shop_buy #商店购买  
      -  
        1: # 第一个tab（通常）购买前四个  
          - 1  
          - 2  
          - 3  
          - 4  
进行时，发现每个位置都偏了，如截图所示：
![image](https://github.com/Gibberer/pcr-script/assets/72589546/c58fa8fd-aff8-4203-ae8f-c3fd419e205c)
![image](https://github.com/Gibberer/pcr-script/assets/72589546/76babf20-3b31-4562-bee5-9ffc1565e342)
猜测是shop_buy一直没有适配新版界面？希望能解答或更新。

**Comment by AlphaBoom** [comment]
是的，不过我没适配原来的方式，因为点“全选”就满足我的需要了。
可以使用新的配置如下，-1表示点击全选按钮，通常和限定Tab可用：
```yml
-
  - shop_buy #商店购买
    -
      1: # 第一个tab（通常）购买前四个
         - -1
```
对应提交：https://github.com/Gibberer/pcr-script/commit/dc6b993c662110a5e8933692f14ceccbbe722a4d

**Comment by madoka315** [comment]
好的。现阶段全选确实也可满足要求了
