### ISSUE TITLE
安装requirement失败了

### ISSUE THREAD

**Issue by skeptic73** [Gibberer/pcr-script#2]
纯萌新，安装requirement里的软件时就失败了。先是显示第一个软件不存在，换成4.3后下载成功，但是安装失败……接着是好几页的红色报错看不懂……如果您还有在玩的话可以麻烦指导一下吗？

**Comment by AlphaBoom** [comment]
指定的版本可能有点问题，你可以看下requirements.txt文件。然后手动安装各个包
```
opencv_python==4.2.0.34
matplotlib==3.1.2
numpy==1.17.3
pywin32==228
PyYAML==5.3.1
```
类似于这样，不指定版本
```
pip install opencv_python matplotlib numpy pywin32 PyYAML
```

**Comment by skeptic73** [comment]
感谢指导，安装成功了，但是脚本还是不能运行，没有操作模拟器。请问是我的python版本有问题吗？
![image](https://user-images.githubusercontent.com/79854907/110410205-7c75b900-80c3-11eb-81c5-e4000137f55a.png)

**Comment by AlphaBoom** [comment]
报错信息是config.yml里的配置文件格式问题有问题，搜索下yaml的格式规范，看下是否哪里写的有问题。

**Comment by skeptic73** [comment]
应该是中文公会名不行hhh删掉了不报错了。期间ADB一直被不知名应用占用，杀进程后终于能运行脚本了。但是卡在第一个wait thread finish，只会一直点左下角。

**Comment by AlphaBoom** [comment]
你可以看下卡在哪个阶段了，执行每个阶段任务都会打印一个start xxxx 然后结束会打印end xxx。
例如切换账号：
```
start changeaccount
end changeaccount
```
方便的话贴下输出日志，配置的话可以贴下Extra以下的部分
```
Extra:
  guildname: &guildname 行会名称 #最好为英文
  dnpath: 'N:\dnplayer2' # 配置雷电模拟器的路径
Task: #配置执行任务,配置任务名称，如果需要传入参数在下面增加参数，可以根据不同的账号序号配置任务。
      #账号会执行小于等于并且离它最近的序号的任务列表
  1: #配置账号大于等于1的进行以下操作
    -
      - get_quest_reward #领取任务奖励
    -
      - tohomepage #回到首页
    -
      - buy_mana #购买mana
      - 20 #买20次
```
这里readme有个地方没写，就是dnpath这里要配置雷电模拟器的安装目录（支持中文输入和快速获取图像）。
然后模拟器屏幕大小设置960x540。

> 这脚本最近一个月没跑过了，我晚上跑下。也可能由于bcr的客服端UI改动照成

**Comment by skeptic73** [comment]
![image](https://user-images.githubusercontent.com/79854907/110467196-ace44400-8111-11eb-9068-095eaa3778f0.png)
谢谢，老哥太上心了。对对，第一步changeaccount就失败了，印象里UI好像也没改过，是不是我哪里设置还有问题？换号和加入公会我也用不到哈，只是自用清清日常。

**Comment by AlphaBoom** [comment]
我测试下来是没有问题的，下面几个点你可以排查下：
1. 启动脚本之前要保证客户端已经打开并停留在游戏的欢迎页面（在游戏内首页也可以，脚本不会主动打开游戏应用）
2. 如果弹出登录框里有之前的登录账号和密码的话，需要手动清空
3. 确保模拟器分辨率是960x540（其他分辨率的行为我不能保证）

然后你如果需要清每日日常的话，可以更新下脚本。我正好最近也要这份功能，所以补全了下。
