### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by kogetsu24** [Gibberer/pcr-script#3]
测试这个自动打轴的时候遇到了一些问题，不知道可不可以通过QQ详细请教一下呢。因为我并不是很懂python，所以只是按照您的说明里按部就班进行操作，现在遇到问题了于是完全手足无措。希望可以得到您的回复 谢谢

**Comment by AlphaBoom** [comment]
你可以把遇到的问题贴在这个Issue下。估计大概就下面几个问题，都可以通过搜索先解决掉。
1.python环境安装
2.脚本依赖库安装，把日常脚本写的依赖加上easyOCR依赖都要安装
3.ADB下载并配置环境变量（打轴这个其实没用到ADB不过也要配置可能会报错）
4.雷电模拟器，并且保证分辨率为960*540

如果有其他问题可以继续补充

**Comment by kogetsu24** [comment]
1 adb已安装 
2 已安装Python3环境  
3 已使用脚本依赖库安装，pip install opencv_python matplotlib numpy pywin32 PyYAML
4 easyOCR依赖安装，pip install easyocr，之后安装 easyocr， 把english_g2.pth放在easyocr\model目录下。（感觉这一步有问题）
5 配置了config文件在pcr-script下
6 配置了autobattle_config在\autobattle目录下

之后开启脚本battle.py

提示 File "C:\Users\akiha\Desktop\PCR\pcr\autobattle\AUTOBATTLE.PY", line 8, in <module>
    from pcrscript.ocr import Ocr
ModuleNotFoundError: No module named 'pcrscript'

麻烦看一下哪一步出了错

**Comment by AlphaBoom** [comment]
你要下载整个工程然后运行，而不是只有autobattle.py这个文件，打轴功能依赖了一些日常脚本的模块。

**Comment by kogetsu24** [comment]
成功运行了main.py之后（可以自动领礼物了），仍然不知道怎么开启autobattle。 在main.py运行的同时去运行autobattle.py吗，仍然提示
Traceback (most recent call last):
  File "C:\Users\akiha\Desktop\PCR\pcr\autobattle\autobattle.py", line 8, in <module>
    from pcrscript.ocr import Ocr
ModuleNotFoundError: No module named 'pcrscript'

**Comment by AlphaBoom** [comment]
不是直接运行autobattle.py，与main.py同目录有一个battle.py执行那个文件

**Comment by kogetsu24** [comment]
谢谢您的指导，已经可以了 非常感谢
