### ISSUE TITLE
请问大神“无效的窗口句柄”怎么解决

### ISSUE THREAD

**Issue by lx442044246** [Gibberer/pcr-script#4]
问下大神 导致这个情况的大概有两种可能性：一是我用的是雷电64位模拟器 第二是部分像素点跟判断不一致 请问这两问题可以通过修改哪个文件解决，非常感谢！

错误代码如下：
fallback adb click:(1400, 'GetWindowRect', '无效的窗口句柄。')

**Comment by AlphaBoom** [comment]
1. 第一个问题检查下雷电模拟器的版本，我目前按照4.0.54版本进行适配的。
2. 第二个问题可能是由于第一个问题导致，可以具体给出像素点判断出错的例子

不想升级雷电模拟器的话，第一个问题可以按下面方式修改：
1. 打开pcr/driver.py文件93行加上这么一句`print(f"{subtitle},{hwnd}")`
    ``` python
    def click(self, x, y):
        if self.click_by_mouse:
            window_title = self._getWindowTitle()
            try:
                hwin = win32gui.FindWindow('LDPlayerMainFrame', window_title)
                self._subhwin = None
                def winfun(hwnd, lparam):
                    subtitle = win32gui.GetWindowText(hwnd)
                    print(f"{subtitle},{hwnd}")
                    if subtitle == 'TheRender':
                        self._subhwin = hwnd
                win32gui.EnumChildWindows(hwin, winfun, None)
    ```
2. 运行脚本，应该会输出如下类似的信息记住
    ```cmd
    TheRender,2360044
    sub,133012
    ```
   对应就是标题和窗口句柄
3. 到雷电模拟器安装目录运行` .\ldconsole.exe list2`会输出下面的数据，2360044就是对应的窗口句柄
   ```
   0,雷电模拟器,7538286,2360044,1,2012,17032
   ```
4. 看下窗口句柄对应的标题是不是`TheRender`，不是的话看1.的代码部分把`TheRender`修改成正确的标题即可。
5. 把1增加的`print(f"{subtitle},{hwnd}")`这行删除

**Comment by lx442044246** [comment]
多谢大神指点，经过排查发现是64位雷电模拟器的名称导致程序无法识别，将一下两行代码做了修改，现在已正常使用。

        window_title = '雷电模拟器(64)'
        hwin = win32gui.FindWindow('LDPlayerMainFrame', "雷电模拟器(64)")

非常感谢大神百忙之中的回复，万分感谢！

**Comment by AlphaBoom** [comment]
获取截屏也是这个方法，你修改下`self._getWindowTitle()`这个方法里面改下名字。名字错了会用慢的方式截屏，你说判断偏差的问题可能是这个
