### ISSUE TITLE
我照着步骤启动脚本后脚本只会点一个地方

### ISSUE THREAD

**Issue by awasl** [Gibberer/pcr-script#5]

**Comment by AlphaBoom** [comment]
由于新版本的游戏客户端登录界面做了修改，所以登录这个操作目前无法执行。

**Comment by awasl** [comment]
那这个脚本现在还能用吗

**Comment by AlphaBoom** [comment]
需要更新脚本来修复，这周末会弄下

**Comment by awasl** [comment]
好的，谢谢大佬

**Comment by AlphaBoom** [comment]
对应修改已提交，拉取新代码之后即可正常登录操作。见： e974e89

**Comment by madoka315** [comment]
我遇到同样问题，但是我引起这个问题是：之前在笔记本连接外接显示器运行正常，拔掉外接显示器运行很多任务都只会点同一个地方，接上显示器又恢复正常（每次操作均重启模拟器与脚本）。
（ps.可能有用的信息：笔记本是不支持独显直连的老型号；该异常情况能百分百复现）
另外当运行不正常的时候，手动截屏发现截屏正常，但貌似就是匹配不了图像。如图是运行回到主页时，只会一直点：
![image](https://github.com/Gibberer/pcr-script/assets/72589546/fba18c20-fbc5-4148-870c-17970a230b37)
![image](https://github.com/Gibberer/pcr-script/assets/72589546/b551102a-cf96-4064-a3d4-490ca8008355)

**Comment by AlphaBoom** [comment]
@madoka315 关于图片获取，默认是不使用ADB的截图而是直接在windows上获取图片。可以尝试先将笔记本屏幕分辨率缩放设置为100%看是否可以正常工作，不过屏幕缩放设置应该是不会影响到截图的。
另外可以尝试使用非ADB模式，配置好雷电模拟器的路径之后使用如下方式启动脚本，该方式使用雷电模拟器的内置工具获取一些有价值的信息，可能可以避免问题。
```PowerShell
python main.py --mode 1
```
