### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by RicardoCZ** [Gibberer/pcr-script#6]
请问按照教程的步骤操作之后打开battle.py或者main.py就闪退是什么原因

**Comment by AlphaBoom** [comment]
使用控制台运行命令执行脚本，失败会有具体的错误日志输出。不会有闪退这类现象

**Comment by RicardoCZ** [comment]
> 使用控制台运行命令执行脚本，失败会有具体的错误日志输出。不会有闪退这类现象

![image](https://user-images.githubusercontent.com/65592453/136653423-6dc53e8a-80e8-49a8-95c5-48af99eb4051.png)

**Comment by AlphaBoom** [comment]
报错是找不到设备，确定模拟器已经打开。控制台输入adb devices看下有没有设备信息。确定能找到设备后再跑脚本，雷电模拟器有时候可能找不到可以尝试重启几次模拟器。

**Comment by RicardoCZ** [comment]
> 报错是找不到设备，确定模拟器已经打开。控制台输入adb devices看下有没有设备信息。确定能找到设备后再跑脚本，雷电模拟器有时候可能找不到可以尝试重启几次模拟器。

![image](https://user-images.githubusercontent.com/65592453/136654255-420be6f8-f8b2-4a0b-9fdc-7a3328cd9469.png)
重启了几次，貌似还是找不到设备

**Comment by AlphaBoom** [comment]
端口被占用了，查下5037端口被哪个进程占用然后关掉对应进程。

**Comment by RicardoCZ** [comment]
![image](https://user-images.githubusercontent.com/65592453/136654850-381b9230-8446-4776-bf61-6f8f68a063a4.png)
我已经通过cmd关掉5037端口的进程了，查找之后也没有显示其他进程了，但是仍然提示

**Comment by AlphaBoom** [comment]
搜索了下报错信息，有一些类似的解答例如：https://blog.csdn.net/figosoar/article/details/41357367 
这个问题属于ADB相关，可以先尝试搜索解决下。
