### ISSUE TITLE
想请问这次又是出现了什么问题

### ISSUE THREAD

**Issue by RicardoCZ** [Gibberer/pcr-script#7]
![image](https://user-images.githubusercontent.com/65592453/136685592-640d2dc3-8d1f-48e3-93fa-bda391bdc557.png)
昨天好不容易可以打开脚本了，今天试着运行又报错了

**Comment by AlphaBoom** [comment]
获取游戏截图报错，见关联Issue: #4 
fallback adb click: (1400, 'GetWindowRect', '无效的窗口句柄') 这个也是类似问题，可以查看关联issue修改title后测试。

如果要使用打轴脚本必须解决这个问题，清日常的话可以使用adb慢慢截图也不影响。

**Comment by RicardoCZ** [comment]
![image](https://user-images.githubusercontent.com/65592453/136700918-b92dee03-a552-4dd8-b45e-057fce0dbefd.png)
目前可以运行了，但是我用例子中c3栞的轴，脚本并不会自动点击（对应位置角色是有技能的）。如果我不暂停的话，点击右上角菜单，脚本会自动帮我返回对战，说明脚本是在正常运行了。我的模拟器分辨率也是按照960x540设置的。

**Comment by RicardoCZ** [comment]
另外，我的上一步操作是和那位老哥一样，将那两行，改成雷电模拟器（64），之后就没有那个无效句柄的报错了

**Comment by AlphaBoom** [comment]
使用最新的代码看看 5125c153f56c56cb0bcaf9d65f8e4c5b4ec24f89
由于截图的方法最近有做修改，图像与之前存在了一定程度的偏移，重新生成了模板图片。
脚本运行期间，能够正常输出：剩余时间xxx的话就代表无问题。
> 还有一个替代的方式是把配置的ocr选项设置为True通过ocr获取当前剩余时间

**Comment by RicardoCZ** [comment]
这边重新下载了整个包之后就出现了这样子的情况
![image](https://user-images.githubusercontent.com/65592453/136707964-6fbae87f-6162-4156-bd06-7397f108600d.png)
以下省略一部分截图，然后是这样
![image](https://user-images.githubusercontent.com/65592453/136707972-92f5d0a3-515d-4a5f-9fa5-d95bada7e8ef.png)
并且过程中也没有点击示例中的轴

**Comment by RicardoCZ** [comment]
我重启了一下好像开始正常运作了
