### ISSUE TITLE
部分情况下ub不释放的现象

### ISSUE THREAD

**Issue by RicardoCZ** [Gibberer/pcr-script#8]
![image](https://user-images.githubusercontent.com/65592453/136746473-d218da3c-8cf2-40d3-ba99-67e7fd6386f3.png)
如果我这么设置的话，5号位置的角色将不释放ub
![image](https://user-images.githubusercontent.com/65592453/136746749-b40bcab2-1eb3-4d4a-b321-08e1b187b935.png)
我看了一下可能由于这条规则的限制，但是4号位置角色的技能是可以正常释放的。还有如果我将listen_mouse_event设置为True时我的battle.py就会出现闪退打不开的情况

**Comment by AlphaBoom** [comment]
listen_mouse_event 是用来辅助找延迟时间的，需要安装鼠标监听的依赖库 `pip install pynput`
同一秒内是可以同时点击多个的，可以通过下面几个方式排查：
* 每次释放UB成功或超时会有`确认{位置}UB释放成功，指定时间xxx`的字样。根据结果看可能有下面几种：
    1. 输出日志，但是实际未点击
    2. 未输出日志，也未点击
    3. 尝试点击了几次，但是未触发UB就提前终止了
    类似上面，描述更具体的场景。
* 尝试同一秒内设置不同的延迟时间，一般同一秒内也会存在先后顺序，我一般使用的时候同一秒也会设置不同的延迟时间来控制UB释放顺序

**Comment by RicardoCZ** [comment]
![image](https://user-images.githubusercontent.com/65592453/136760466-ca1c0f30-01a4-4af1-afa7-7a938b876c09.png)
在我开启了角色ub动画的情况下，83秒释放出2号位置的ub仍然持续点击了游戏内时间的一秒，也就是点击持续到82秒，而82秒仍然只点击了轴更靠下方的四号位置的ub，即使我设置成  82 5 0.4    82  4 0.5  仍然只点击四号位置。
在我删除四号位置的轴后，83秒释放完2号ub，仍然不点击五号位置

**Comment by AlphaBoom** [comment]
我觉得可能是设置时间间隔过小，但是点击耗时过长导致。比如4ub等到79秒才打印释放成功，正常来说已经到了超时的时间。
你在autobattle.py 文件里找到
```python
    def _waitnext(self, starttime):
        consume = time.time() - starttime
        if consume < INTERVAL:
            time.sleep(INTERVAL - consume)
        else:
            # print(f"卡帧：{consume}")
            pass
```
把注释打开，修改为
```python
    def _waitnext(self, starttime):
        consume = time.time() - starttime
        if consume < INTERVAL:
            time.sleep(INTERVAL - consume)
        else:
            print(f"卡帧：{consume}")
            pass
```
如果频繁显示卡帧，就把点击时间间隔和 读取时间间隔调大一些。修改时保证 读取时间间隔>=点击时间间隔。

**Comment by RicardoCZ** [comment]
这边尝试删除注释之后运行，只在刚开始运行脚本时，提示卡帧，后续都没有提示，但是后面仍然跟之前一样。我想了解一下，怎么将连续点击持续的时间缩短一点，每次任意位置的ub连续点击都会持续好几秒，怎么才能做到尽量缩短ub后继续连续点击的时间

**Comment by RicardoCZ** [comment]
请问大佬方便通过远程桌面的方式看看到底是哪里的问题吗

**Comment by AlphaBoom** [comment]
连续点击的下限是到下一秒，上限是配置的超时时间。你说5号位置没有释放那有没有五号位置ub超时的日志。可以把轴和配置发我，我有时间测试下

**Comment by RicardoCZ** [comment]
"炸脖龙":
        - 83 2
        - 82 5 0.5
        - 82 4 0.5
        - 79 3
        - 73 1
        - 66 4
提前存满tp的五个角色，安，似似花，春田，水壶，猫仓唯

**Comment by RicardoCZ** [comment]
日志就是上面的最后一张截图

**Comment by AlphaBoom** [comment]
更新下看看吧 点击好几秒的问题还是由于修改截图方法之后导致的问题  8b0fbe31ba6cc5d7a35574672481c4d142df9fed

另一个问题是5号位置不能点击是由于最小点击间隔过小导致，这个地方我先修改为0.015，如果还有未点击的问题可以修改autobattle.py这个位置的代码
```
    def _clickub(self, index):
        x, y = self._pos(*UB_LOCATIONS[index])
        self._driver.click(x, y)
        time.sleep(0.015)
```
试了一下0.01雷电模拟器会崩溃。这里建议时间调节为0.01到0.1之间吧

> 如果最低点一秒的时间也不想要的话，可以修改这个值为0（没有弄到配置文件，需要修改代码, 在autobattle.py文件的开头位置）
>```
>UB_MIN_CHECK_DURATION = 1
>-------
>UB_MIN_CHECK_DURATION = 0
>```

**Comment by RicardoCZ** [comment]
我这边把64位的模拟器卸载了，下载了和大佬一样的版本，希望一会安装完游戏没有其他问题了QAQ
